//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcerUserSensing.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcerUserSensing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Change settings 的當地語系化字串。
        /// </summary>
        public static string strChangeSetting {
            get {
                return ResourceManager.GetString("strChangeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Automatically disable Acer User Sensing when not connected to a charger 的當地語系化字串。
        /// </summary>
        public static string strConfigCharger {
            get {
                return ResourceManager.GetString("strConfigCharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep Acer User Sensing enabled when connected to an external monitor 的當地語系化字串。
        /// </summary>
        public static string strConfigExternalMonitor {
            get {
                return ResourceManager.GetString("strConfigExternalMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Immediately 的當地語系化字串。
        /// </summary>
        public static string strImmediate {
            get {
                return ResourceManager.GetString("strImmediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acer User Sensing technology allows your laptop to detect when you’re near or far, allowing you to quickly login as you approach or lock as you leave. 的當地語系化字串。
        /// </summary>
        public static string strIntro {
            get {
                return ResourceManager.GetString("strIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Off 的當地語系化字串。
        /// </summary>
        public static string strOff {
            get {
                return ResourceManager.GetString("strOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 On 的當地語系化字串。
        /// </summary>
        public static string strOn {
            get {
                return ResourceManager.GetString("strOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Seconds 的當地語系化字串。
        /// </summary>
        public static string strSecond {
            get {
                return ResourceManager.GetString("strSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Maximize security and your battery life by having your system lock itself when you&apos;re not around. Select from the options below to adjust the time it takes until your system automatically dims and locks. 的當地語系化字串。
        /// </summary>
        public static string strWalDesc {
            get {
                return ResourceManager.GetString("strWalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dim Delay 的當地語系化字串。
        /// </summary>
        public static string strWalDimDelay {
            get {
                return ResourceManager.GetString("strWalDimDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lock Delay after Dimming 的當地語系化字串。
        /// </summary>
        public static string strWalLockDelay {
            get {
                return ResourceManager.GetString("strWalLockDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AutoLock 的當地語系化字串。
        /// </summary>
        public static string strWalTitle {
            get {
                return ResourceManager.GetString("strWalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Windows Hello™ biometrics sign-in requires specialized hardware, including a Windows Hello capable device, fingerprint reader, illuminated IR sensor, or other biometric sensors. 的當地語系化字串。
        /// </summary>
        public static string strWindowHelloDesc {
            get {
                return ResourceManager.GetString("strWindowHelloDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow your laptop to wake itself the moment it senses your presence automatically. Make use of {0} for an even more seamless user experience. 的當地語系化字串。
        /// </summary>
        public static string strWoaDesc {
            get {
                return ResourceManager.GetString("strWoaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wake on Approach 的當地語系化字串。
        /// </summary>
        public static string strWoaTitle {
            get {
                return ResourceManager.GetString("strWoaTitle", resourceCulture);
            }
        }
    }
}
